// Package pr implements the `pr` step type: it takes the agent's modified working tree
// and turns it into a pull request. PR_MODE=github (the GitHub-native product default in
// prod) opens a real PR via `gh` and, when the step sets `merge: true`, merges it. PR_MODE=
// local commits+pushes a branch WITHOUT opening a PR — for offline dev/tests only; running
// it against a real GitHub origin silently strands the branch (see the loud guard in Run).
package pr

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"forge/internal/workflow"
)

// Runner implements workflow.Runner for `pr` steps.
type Runner struct {
	// Mode is "github" (prod: open+merge real PRs) or "local" (offline dev/tests only).
	Mode string
}

// NewRunner builds a PR runner. Mode defaults to PR_MODE env or "local".
func NewRunner() *Runner {
	mode := os.Getenv("PR_MODE")
	if mode == "" {
		mode = "local"
	}
	return &Runner{Mode: mode}
}

// Run implements workflow.Runner.
func (r *Runner) Run(ctx context.Context, step workflow.Step, inputs map[string]any, workdir string) (workflow.StepResult, error) {
	runID := filepath.Base(workdir)
	// Branch is per-SPRINT when the step carries a sprint ref (resumable sprints:
	// the same branch is reused/force-pushed across a sprint's runs), else per-run.
	branch := "vibeforge/" + runID
	if s, ok := inputs["branch_ref"].(string); ok && s != "" {
		branch = "vibeforge/sprint_" + s
	}

	if !isGitRepo(ctx, workdir) {
		// No repo seeded (e.g. stub flows): record a synthetic local PR so the
		// flow completes deterministically.
		return workflow.StepResult{
			Success: true,
			Output:  map[string]any{"pr": "local-synthetic", "branch": branch, "mode": r.Mode, "committed": false},
			Detail:  "pr(local): no git repo in workdir; recorded synthetic PR",
		}, nil
	}

	msg := commitMessage(inputs, runID)
	// gitRun prepends "git" — these are the args AFTER it.
	steps := [][]string{
		{"checkout", "-B", branch},
		{"add", "-A"},
		{"-c", "user.email=kernel@vibeforge", "-c", "user.name=vibeforge", "commit", "-m", msg, "--allow-empty"},
	}
	var log strings.Builder
	for _, s := range steps {
		out, err := gitRun(ctx, workdir, s...)
		log.WriteString(out)
		if err != nil {
			return workflow.StepResult{Success: false, Detail: "pr(local) failed at `git " + strings.Join(s, " ") + "`: " + err.Error() + "\n" + out}, nil
		}
	}

	pushed := false
	if hasRemote(ctx, workdir, "origin") {
		if out, err := gitRun(ctx, workdir, "push", "-f", "origin", branch); err != nil {
			log.WriteString(out)
			return workflow.StepResult{Success: false, Detail: "pr(local) push failed: " + err.Error() + "\n" + out}, nil
		}
		pushed = true
	}

	head, _ := gitRun(ctx, workdir, "rev-parse", "HEAD")

	// `merge: true` (the design docs_pr) means the PR must be opened AND merged into base —
	// any failure is TERMINAL (the step fails), so nothing downstream (handoff, sprint
	// dispatch) proceeds on a base branch that lacks the docs. Without it (factory code PRs)
	// a failed create stays non-fatal: the branch is pushed and the conductor drives the merge.
	mustMerge := truthy(inputs["merge"])
	base := ""
	if b, ok := inputs["base"].(string); ok {
		base = b
	}

	// PR_MODE=local against a REAL GitHub origin silently strands the branch off the base
	// branch (no PR is opened). Harmless for offline dev (local/temp remote), but in
	// production it's the reservas-belleza incident (2026-07-06). Make it LOUD — and
	// hard-fail if a merge was required, so docs can never silently miss `main`.
	if pushed && r.Mode != "github" && originIsGitHub(ctx, workdir) {
		warn := "PR_MODE=" + r.Mode + " but origin is GitHub: branch pushed WITHOUT opening a PR. Set PR_MODE=github."
		if mustMerge {
			return workflow.StepResult{Success: false, Detail: "pr: " + warn + " A merge into `" + base + "` was required but local mode can't open/merge a PR. Branch: " + branch}, nil
		}
		log.WriteString("WARNING: " + warn)
	}

	// GitHub mode: open the PR (gh infers the repo from origin); `base` selects the target.
	prURL := ""
	if pushed && r.Mode == "github" {
		title := strings.TrimPrefix(commitMessage(inputs, runID), "vibeforge: ")
		body := "Generated by the aiuda-forge factory.\n\nRun: " + runID
		ghArgs := []string{"pr", "create", "--head", branch, "--title", title, "--body", body}
		if base != "" {
			ghArgs = append(ghArgs, "--base", base)
		}
		out, err := ghRun(ctx, workdir, ghArgs...)
		if err != nil {
			// A PR already open for this head (idempotent re-run) is fine — we can still merge it.
			if !strings.Contains(out, "already exists") {
				if mustMerge {
					return workflow.StepResult{Success: false, Detail: "pr(github) create failed: " + err.Error() + "\n" + out}, nil
				}
				log.WriteString("gh pr create: " + err.Error() + "\n" + out)
			}
		} else {
			prURL = lastURL(out)
		}

		// Auto-merge the docs PR: every design phase was already human-gated, so the PR
		// carries no new decision — merging it lands docs/ on `base` (the canonical spec
		// the sprint agents read). If it fails, the whole step fails (docs NOT on main).
		if mustMerge {
			mout, merr := ghRun(ctx, workdir, "pr", "merge", branch, "--merge")
			if merr != nil {
				return workflow.StepResult{Success: false, Detail: "pr(github) merge failed (docs not on `" + base + "`): " + merr.Error() + "\n" + mout}, nil
			}
		}
	}

	detail := fmt.Sprintf("pr(%s): committed to %s (pushed=%v)", r.Mode, branch, pushed)
	if prURL != "" {
		detail = fmt.Sprintf("pr(github): opened %s", prURL)
	}
	merged := mustMerge && r.Mode == "github"
	if merged {
		detail += " · merged into " + base
	}
	return workflow.StepResult{
		Success: true,
		Output: map[string]any{
			"pr": branch, "branch": branch, "mode": r.Mode, "url": prURL,
			"committed": true, "pushed": pushed, "head": strings.TrimSpace(head), "merged": merged,
		},
		Detail: detail,
	}, nil
}

// truthy interprets a YAML input as a boolean (accepts bool or a non-negative string).
func truthy(v any) bool {
	switch x := v.(type) {
	case bool:
		return x
	case string:
		s := strings.ToLower(strings.TrimSpace(x))
		return s != "" && s != "false" && s != "no" && s != "0"
	}
	return false
}

// originIsGitHub reports whether the workdir's origin remote points at github.com — used to
// tell "offline local dev" (fine in local mode) from "production misconfigured to local mode".
func originIsGitHub(ctx context.Context, workdir string) bool {
	out, err := gitRun(ctx, workdir, "remote", "get-url", "origin")
	if err != nil {
		return false
	}
	return strings.Contains(out, "github.com")
}

// ghRun runs the `gh` CLI in workdir (which infers the repo from origin).
func ghRun(ctx context.Context, workdir string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, "gh", args...)
	cmd.Dir = workdir
	var buf bytes.Buffer
	cmd.Stdout, cmd.Stderr = &buf, &buf
	err := cmd.Run()
	return buf.String(), err
}

// lastURL returns the last https URL line in gh's output (the PR URL).
func lastURL(out string) string {
	url := ""
	for _, line := range strings.Fields(out) {
		if strings.HasPrefix(line, "https://") {
			url = line
		}
	}
	return url
}

func commitMessage(inputs map[string]any, runID string) string {
	if t, ok := inputs["ticket"].(string); ok && t != "" {
		first := t
		if i := strings.IndexByte(t, '\n'); i > 0 {
			first = t[:i]
		}
		return "vibeforge: " + strings.TrimSpace(first)
	}
	return "vibeforge: run " + runID
}

func isGitRepo(ctx context.Context, workdir string) bool {
	_, err := gitRun(ctx, workdir, "rev-parse", "--is-inside-work-tree")
	return err == nil
}

func hasRemote(ctx context.Context, workdir, name string) bool {
	out, err := gitRun(ctx, workdir, "remote")
	if err != nil {
		return false
	}
	for _, line := range strings.Fields(out) {
		if line == name {
			return true
		}
	}
	return false
}

func gitRun(ctx context.Context, workdir string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = workdir
	var buf bytes.Buffer
	cmd.Stdout, cmd.Stderr = &buf, &buf
	err := cmd.Run()
	return buf.String(), err
}
