// Generated by supabase-dev via `supabase gen types typescript --local`.
// This is a hand-written stub for the demo; in a real project it is generated
// output and consumed read-only by the react-dev lane. It mirrors the shape the
// Supabase CLI emits so `createClient<Database>()` is fully typed.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      todos: {
        Row: {
          id: string;
          owner_id: string;
          title: string;
          done: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          done?: boolean;
        };
        Update: {
          title?: string;
          done?: boolean;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
